In [85]:
import numpy as np

In [86]:
# NP.ARRAY
x = np.array([[1,2,3,4,5], [6,7,8,9,3]])
print(x)
print(type(x))

[[1 2 3 4 5]
 [6 7 8 9 3]]
<class 'numpy.ndarray'>


In [87]:
# NP.ZEROS

zero_array = np.zeros(shape=(5,3,6))
print(zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [88]:
# NP.ONES

um_array = np.ones(shape=(2,3,4))
print(um_array)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [89]:
# NP.EMPTY

vazio = np.empty((3,4))
print(vazio)

[[4.9e-324 9.9e-324 1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323 4.9e-324 2.0e-323]
 [2.5e-323 3.0e-323 3.5e-323 4.0e-323]]


In [90]:
# NP.ARANGE

# Ao inves de utilizar desta forma 
# ⬇
t1 = np.array([1,2,3,4,5,6])
print(t1)

# Podemos utilizar desta forma
# ⬇
t2 = np.arange(3)
print(t2)

# Star -> posição  = a partir de quando vai começar a contagem
# Step -> contador = número que vai ser contado (se step = 2, a contagem será de 2 em 2)
# Stop ->   fim    = onde é encerrado a contagem do número
t3 = np.arange(start =2, step =2, stop =51)
print(t3)

[1 2 3 4 5 6]
[0 1 2]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [106]:
# NP.LINSPACE

array_linear = np.linspace(0, 100, num=40, endpoint= True)
print(array_linear)

[  0.           2.56410256   5.12820513   7.69230769  10.25641026
  12.82051282  15.38461538  17.94871795  20.51282051  23.07692308
  25.64102564  28.20512821  30.76923077  33.33333333  35.8974359
  38.46153846  41.02564103  43.58974359  46.15384615  48.71794872
  51.28205128  53.84615385  56.41025641  58.97435897  61.53846154
  64.1025641   66.66666667  69.23076923  71.79487179  74.35897436
  76.92307692  79.48717949  82.05128205  84.61538462  87.17948718
  89.74358974  92.30769231  94.87179487  97.43589744 100.        ]


In [107]:
# Descobrindo o tamanho do array

zero_array = np.zeros(shape=(5,3,6))
print(zero_array)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [ ]:
# Formato do array
print(zero_array.shape)

# Quantidade de dados do array 
print(zero_array.size)

# Número de dimensões
print(zero_array.ndim)

(5, 3, 6)
90
3
